name:  Bug Report
description: Reportar un error o comportamiento inesperado
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug. Por favor completa la informaci贸n para ayudarnos a resolverlo.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Bug
      description: Describe claramente qu茅 est谩 fallando
      placeholder: Al ejecutar X, esperaba Y pero obtuve Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir
      description: Pasos detallados para reproducir el problema
      placeholder: |
        1. Ejecutar '...'
        2. Click en '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Qu茅 deber铆a pasar
      placeholder: Deber铆a copiar los archivos sin errores...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Qu茅 est谩 pasando realmente
      placeholder: Se muestra error "..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Contenido relevante de C:\Llevar\Logs\LLEVAR_*.log
      render: shell
      placeholder: Pega aqu铆 el contenido del log...

  - type: input
    id: powershell-version
    attributes:
      label: Versi贸n de PowerShell
      description: Ejecuta `$PSVersionTable.PSVersion` y pega el resultado
      placeholder: "7.4.0"
    validations:
      required: true

  - type: input
    id: windows-version
    attributes:
      label: Versi贸n de Windows
      description: Ejecuta `[System.Environment]::OSVersion.Version` y pega el resultado
      placeholder: "10.0.22631.0"
    validations:
      required: true

  - type: dropdown
    id: transfer-type
    attributes:
      label: Tipo de Transferencia
      description: 驴Qu茅 tipo de transferencia estabas realizando?
      options:
        - Local a Local
        - Local a USB
        - Local a FTP
        - Local a OneDrive
        - Local a Dropbox
        - Local a ISO
        - FTP a FTP
        - FTP a Local
        - Otro
    validations:
      required: false

  - type: checkboxes
    id: compression
    attributes:
      label: Opciones Usadas
      description: Marca las opciones que estabas usando
      options:
        - label: Compresi贸n 7-Zip
        - label: Divisi贸n de bloques
        - label: Modo interactivo
        - label: Modo normal (par谩metros)

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n Adicional
      description: Cualquier otra informaci贸n relevante (capturas de pantalla, configuraci贸n especial, etc.)
